on:
  push:
    branches: actions-tests

jobs:

  test-backend:
  
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Build and test backend
        run: mvn clean test

      - name: Generate JaCoCo test coverage report
        run: mvn jacoco:report
