on: 
  push: 
    branches: actions-tests

jobs: 

  call-worklow-backend-tests:
    uses: ./.github/workflows/backEndTests.yml

  call-worklow-frontend-tests:
    uses: ./.github/workflows/frontEndTests.yml
  
  call-worklow-docker:
    needs: [call-worklow-backend-tests, call-worklow-frontend-tests]
    uses: ./.github/workflows/docker.yml
    secrets: inherit
